---
name: ci
on:
  - push
  - pull_request
env:
  golang-version: '1.20'
jobs:
  generate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    name: Generate
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ env.golang-version }}
    - run: go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
    - run: make generate
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ env.golang-version }}
    - run: go install github.com/google/go-jsonnet/cmd/jsonnet@latest
    - run: make build
